pipeline {
    agent {label 'slave' }

    stages {
        stage('Build image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker_cer', passwordVariable: 'pass', usernameVariable: 'user')])       {
    		sh """
    		    docker build . -t som3a97/gradapp:${BUILD_NUMBER}
    		    docker login -u ${user} -p ${pass}
    		    docker push som3a97/gradapp:${BUILD_NUMBER}
    		    echo done
    		"""
                }
            }
        }
        stage ('deploy app'){
            steps {
                sh """
                kubectl apply -f app.yml
                echo done
            """
            }
        }
        }
    }

	
