- name: Install packages that allow apt to be used over HTTPS
  become: true
  apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - lsb-release


- name: Add an apt signing key for Docker
  become: true
  apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      state: present

- name: Add apt repository for stable version
  become: true
  apt_repository:
      repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} $(lsb_release -cs) stable"
      state: present

- name: update
  become: true
  apt:
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: 3600

- name: Install docker and its dependecies
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io