- hosts: all
  remote_user: timon
  tasks:
  - name: deploy jenkins pods
    k8s:
        api_version: v1
        namespace: jenkinsnamespace
        definition:
          kind: Deployment
          metadata:
            labels:
              app: jenkins
            name: jenkins
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: jenkins
            template:
              metadata:
                labels:
                  app: jenkins
              spec:
                containers:
                - image: jenkins/jenkins:lts-jdk11
                  name: jenkins
                  resources: {}
                  ports:
                  - containerPort: 8080
                  readinessProbe:
                    failureThreshold: 5
                    httpGet:
                      path: /login
                      port: 8080
                      scheme: HTTP
                    periodSeconds: 10
                    successThreshold: 2
                    timeoutSeconds: 5