- hosts: all
  remote_user: timon
  tasks:
  - name: deploy jenkins pods
    k8s:
        api_version: v1
        namespace: jenkinsnamespace
        definition:
          kind: Service
          metadata:
            name: app-loadblancer	
          spec:
            type: LoadBalancer
            selector:
              app: jenkins
            ports:
              - protocol: TCP
                port: 8080
                targetPort: 8080